### ISSUE TITLE
Add some of the required docs/minimum code requirements

### ISSUE THREAD

**Issue by arrooney** [AlbertaSat/ex2_sband_software#1]
You should add a few things to this repo to make officially great.
* Contributing.md file: this pops up as a reminder to people making a PR in the future, and you can just copy it from [here](https://github.com/AlbertaSat/ex2_command_handling_demo/blob/dev/contributing.md)
* clang-format linter, which will fix your code style for you, you can just copy [this](https://github.com/AlbertaSat/ex2_command_handling_demo/blob/dev/.clang-format) file; I've set up git hooks so that it runs this file on a git commit, but I guess this isn't versioned in git so we'll leave that for now.
* we might consider putting your tests in jenkins (if only just for a demo for later repositories), we have a jenkins server [here](http://165.227.49.142:8080/) - I can show you how to automate jenkins if you've never seen this before

**Comment by tganley** [comment]
Those two files should be there now and I added all the comments and stuff. Forgot to respond to this issue. Never seen Jenkins but it sounds cool
